language: java
install: mvn install --quiet -DskipTests=true -B
script: mvn test --quiet -B
jdk:
  - openjdk7
  - oraclejdk7
# Karaf 2.3.x does not support Java 8
# https://issues.apache.org/jira/browse/KARAF-2602
#  - oraclejdk8
notifications:
  slack: connexta:81WapNypxEStYlHEnsrCml7n
